### ISSUE TITLE
The script errors out if game_info.image is None

### ISSUE THREAD

**Issue by cklenetsky** [RKDN/bgg_collection2pdf#15]
My entry for "Funkoverse Strategy Game: Space Jam A New Legacy 100" returns nothing back for the image URL.  The script then errors out with:

```
Traceback (most recent call last):
  File "./generate_pdf.py", line 463, in <module>
    download_image(config, game_info)
  File "./generate_pdf.py", line 227, in download_image
    res = requests.get(game_info.image, stream = True)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 382, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

I got around the error with a simple None check in download_image, though the resulting output still reference a non-existent image:

```
            #Download the image to the local cache.
            if (game_info.image is None):
                logging.warning(game_info.name + " has no image url")
            else:
                res = requests.get(game_info.image, stream = True)
                if res.status_code == 200:
                    logging.info("Writing: " + collection_info.game_name + " boxart to " + os.path.join(config.images_path, game_info.obj_id + ".jpg"))
                    with open(os.path.join(config.images_path, game_info.obj_id + ".jpg"), 'wb') as f:
                        shutil.copyfileobj(res.raw, f)
```
Perhaps adding a "no image" placeholder jpg and referencing that in the output in this case?

**Comment by cklenetsky** [comment]
As an alternative, I'm grabbing BGG's "No Image Available" image instead:

```
            #Download the image to the local cache.
            if (game_info.image is None):
                logging.warning(game_info.name + " has no image url")
                game_info.image = "https://cf.geekdo-images.com/zxVVmggfpHJpmnJY9j-k1w__imagepagezoom/img/RO6wGyH4m4xOJWkgv6OVlf6GbrA=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic1657689.jpg"
            res = requests.get(game_info.image, stream = True)
            if res.status_code == 200:
```

though this solution is certainly brittle if something changes on BGG's side.
