### ISSUE TITLE
'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by kberg** [RKDN/bgg_collection2pdf#9]
```
$ python generate_pdf.py 
WARNING:root:UserName:  was not valid
Enter your BGG UserName: rkonigsberg
INFO:root:UserName: rkonigsberg is valid
INFO:root:starting
WARNING:root:Reading collection from bgg
Traceback (most recent call last):
  File "generate_pdf.py", line 377, in <module>
    items = read_collection(config)
  File "generate_pdf.py", line 273, in read_collection
    collection_response = bgg_getter('collection',params, config)
  File "generate_pdf.py", line 97, in bgg_getter
    logging.info("Sleeping " + str(config.sleep_time) + " Seconds: " + (error.find('message').text if error != None else str(status)))
AttributeError: 'NoneType' object has no attribute 'text'
$
```

**Comment by kberg** [comment]
I can't recreate the issue now, but that bit of code in `logging.info` definitely assumes that `'message'` appears in the output, when it might not.

**Comment by ejamer** [comment]
This can be closed after recent merge.
